"""add_marketplace_tables

Revision ID: 6d47f7bd5a0c
Revises: '75ae883e2491'
Create Date: 2026-08-06 15:42:54.105921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d47f7bd5a0c'
down_revision: Union[str, None] = '75ae883e2491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_items_id'), 'marketplace_items', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_items_is_active'), 'marketplace_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketplace_items_is_sold'), 'marketplace_items', ['is_sold'], unique=False)
    op.create_index(op.f('ix_marketplace_items_price'), 'marketplace_items', ['price'], unique=False)
    op.create_index(op.f('ix_marketplace_items_title'), 'marketplace_items', ['title'], unique=False)
    op.create_index(op.f('ix_marketplace_items_user_id'), 'marketplace_items', ['user_id'], unique=False)
    op.create_table('marketplace_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_images_id'), 'marketplace_images', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_images_item_id'), 'marketplace_images', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_images_item_id'), table_name='marketplace_images')
    op.drop_index(op.f('ix_marketplace_images_id'), table_name='marketplace_images')
    op.drop_table('marketplace_images')
    op.drop_index(op.f('ix_marketplace_items_user_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_title'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_price'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_is_sold'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_is_active'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    # ### end Alembic commands ###
