"""create housing listings and images tables

Revision ID: 75ae883e2491
Revises: 'ab6aeceeb114'
Create Date: 2026-07-26 22:09:22.373060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ae883e2491'
down_revision: Union[str, None] = 'ab6aeceeb114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_type', sa.String(length=30), nullable=False),
    sa.Column('rent_per_person', sa.Integer(), nullable=False),
    sa.Column('security_deposit', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('sharing_type', sa.String(length=20), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('pref_veg', sa.Boolean(), nullable=True),
    sa.Column('pref_smoking', sa.Boolean(), nullable=True),
    sa.Column('pref_study_friendly', sa.Boolean(), nullable=True),
    sa.Column('pref_sleep_schedule', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_listings_distance_km'), 'housing_listings', ['distance_km'], unique=False)
    op.create_index(op.f('ix_housing_listings_id'), 'housing_listings', ['id'], unique=False)
    op.create_index(op.f('ix_housing_listings_is_active'), 'housing_listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_housing_listings_listing_type'), 'housing_listings', ['listing_type'], unique=False)
    op.create_index(op.f('ix_housing_listings_rent_per_person'), 'housing_listings', ['rent_per_person'], unique=False)
    op.create_index(op.f('ix_housing_listings_user_id'), 'housing_listings', ['user_id'], unique=False)
    op.create_table('housing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['housing_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_images_id'), 'housing_images', ['id'], unique=False)
    op.create_index(op.f('ix_housing_images_listing_id'), 'housing_images', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_housing_images_listing_id'), table_name='housing_images')
    op.drop_index(op.f('ix_housing_images_id'), table_name='housing_images')
    op.drop_table('housing_images')
    op.drop_index(op.f('ix_housing_listings_user_id'), table_name='housing_listings')
    op.drop_index(op.f('ix_housing_listings_rent_per_person'), table_name='housing_listings')
    op.drop_index(op.f('ix_housing_listings_listing_type'), table_name='housing_listings')
    op.drop_index(op.f('ix_housing_listings_is_active'), table_name='housing_listings')
    op.drop_index(op.f('ix_housing_listings_id'), table_name='housing_listings')
    op.drop_index(op.f('ix_housing_listings_distance_km'), table_name='housing_listings')
    op.drop_table('housing_listings')
    # ### end Alembic commands ###
